[profile.default]
solc = "0.8.19"
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [{ access = "read-write", path = "./env/"}]

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = 'short'
# See more config options https://github.com/foundry-rs/foundry/tree/master/config